import {calculateVolume} from '../prototype/quote-volume.mjs';
import {offerService} from '../offers.mjs';
import {test} from 'node:test';import assert from 'node:assert/strict';import {createTenantStore} from '../tenant-store.mjs';import {quoteService,validateQuote,matchCarriers} from '../quotes.mjs';import {portalOperations} from '../operations.mjs';
const request={company:'Müşteri A',person:'Test Yetkili',email:'customer@example.com',phone:'5550000000',direction:'İthalat',mode:'Kara',originCountry:'Almanya',originCity:'Berlin',originAddress:'Yükleme adresi',destinationCountry:'Türkiye',destinationCity:'İstanbul',destinationAddress:'Teslim adresi',goods:'Makine parçası',packages:'2',gross:'120',net:'100',volume:'2',dimensions:'100 x 100 x 100 cm',readyDate:'2026-10-01',incoterm:'FCA'};
const carrier=(id,mode,email)=>({id,name:id,isCarrier:true,serviceCountries:['Almanya'],contacts:[{first:'Test',transportMode:mode,email}]});
test('quote fields are mandatory and invalid weights cannot create drafts',()=>{for(const key of Object.keys(request).filter(k=>k!=='volume'))assert.throws(()=>validateQuote({...request,[key]:''}));assert.throws(()=>validateQuote({...request,net:'200'}));assert.equal(matchCarriers([carrier('a','Hava','a@example.com')],request).length,0);});
test('each matching carrier gets an isolated reviewed draft, no match is actionable',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,admin=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(admin,{_revision:store.revision(),companies:[carrier('a','Kara','a@example.com'),carrier('b','Kara','b@example.com'),carrier('c','Hava','c@example.com')]});const quotes=quoteService(store);const result=quotes.create(admin,request);assert.equal(result.carrierCount,2);const row=quotes.list(admin)[0];assert.deepEqual(row.drafts.map(d=>d.body.to[0]).sort(),['a@example.com','b@example.com']);assert.ok(row.drafts.every(d=>!d.body.text.includes('customer@example.com')));assert.equal(portalOperations(store).outbox(admin).length,0);assert.throws(()=>quotes.approve({...admin,role:'Operasyon'},{id:row.drafts[0].id,reviewed:true,subject:'A',text:'B'}),e=>e.status===403);quotes.approve(admin,{id:row.drafts[0].id,reviewed:true,subject:'Fiyat talebi',text:row.drafts[0].body.text});assert.equal(portalOperations(store).outbox(admin).length,1);assert.equal(quotes.create(admin,{...request,originCountry:'Japonya'}).status,'needs-carrier');}finally{store.close();}});

test('offers enforce admin access, revisions and reviewed idempotent mail',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,u=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(u,{companies:[carrier('a','Kara','a@example.com')]});const q=quoteService(store).create(u,request),svc=offerService(store);assert.throws(()=>svc.list({...u,role:'Operasyon'}),e=>e.status===403);assert.throws(()=>svc.list({...u,role:'Müşteri'}),e=>e.status===403);const body={quoteId:q.id,carrierId:'a',purchase:'100.25',sale:'150',currency:'EUR',validUntil:'2026-10-01',status:'Teklif geldi'};assert.throws(()=>svc.save(u,{...body,purchase:'1.234'}));const saved=svc.save(u,body);assert.equal(svc.list(u)[0].body.purchase,100.25);assert.throws(()=>svc.save(u,{...body,id:saved.id,version:0}),e=>e.status===409);const mail={...saved,to:'customer@example.com',subject:'Teklif',text:'Navlun 150 EUR'};assert.throws(()=>svc.send(u,mail));svc.send(u,{...mail,reviewed:true});svc.send(u,{...mail,reviewed:true});assert.equal(portalOperations(store).outbox(u).length,1);assert.equal(svc.list(u)[0].mail.status,'waiting-provider');}finally{store.close();}});

test('incoming carrier price can be saved before customer price exists',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,u=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(u,{companies:[carrier('a','Kara','a@example.com')]});const q=quoteService(store).create(u,request),svc=offerService(store);const saved=svc.save(u,{quoteId:q.id,carrierId:'a',purchase:'100',sale:'',currency:'EUR',validUntil:'2026-10-01',status:'Teklif geldi'});assert.equal(svc.list(u)[0].body.sale,null);assert.throws(()=>svc.send(u,{...saved,reviewed:true,to:'customer@example.com',subject:'Test',text:'Test'}));}finally{store.close();}});

test('volume derives from cm dimensions and validates mixed package counts',()=>{assert.equal(calculateVolume('120 x 80 x 150',12),17.28);assert.equal(calculateVolume('3 adet: 120 x 80 x 150; 2 adet: 100 x 80 x 90',5),5.76);assert.equal(calculateVolume('100,5 x 100 x 100',1),1.005);assert.throws(()=>calculateVolume('3 adet: 120 x 80 x 150',5));assert.throws(()=>calculateVolume('0 x 80 x 150',1));assert.equal(validateQuote({...request,volume:'999'}).volume,'2');});

test('representatives may serve several selected modes and retain legacy selections',()=>{const company=carrier('multi','Kara','multi@example.com');company.contacts[0].transportModes=['Kara','Hava'];assert.equal(matchCarriers([company],request).length,1);assert.equal(matchCarriers([company],{...request,mode:'Hava'}).length,1);assert.equal(matchCarriers([company],{...request,mode:'Deniz'}).length,0);company.contacts[0].transportModes=[];assert.equal(matchCarriers([company],request).length,0);delete company.contacts[0].transportModes;assert.equal(matchCarriers([company],request).length,1);});

// Siteden gelen talep sahibine bir onay yollanir. Bu posta musteriye gider, bu
// yuzden hangi acenteye sorulacagini asla icermemelidir.
test('website intake acknowledges the requester once and never names the carrier',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,admin=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(admin,{companies:[carrier('Gizli Acente','Kara','gizli@example.com')]});const quotes=quoteService(store);const result=quotes.intake({...request,email:'Musteri@Example.COM'});const queue=portalOperations(store).outbox(admin);assert.equal(queue.length,1);const ack=queue[0].payload;assert.equal(ack.kind,'quote-ack');assert.deepEqual(ack.to,['musteri@example.com']);assert.ok(ack.subject.includes(result.id));assert.ok(ack.text.includes(result.id));assert.ok(!ack.text.includes('Gizli Acente'));assert.ok(!ack.text.includes('gizli@example.com'));
 // Ayni referans icin ikinci bir onay kuyruga girmemeli.
 store.database.db.prepare("INSERT OR IGNORE INTO outbox VALUES('dup','quote-ack:'||?,'waiting-provider',0,?,'{}',NULL)").run(result.id,new Date().toISOString());assert.equal(store.database.db.prepare("SELECT count(*) n FROM outbox WHERE unique_key LIKE 'quote-ack:%'").get().n,1);
 // Onay postasinin eki yoktur; teslim yolu PDF aramaya kalkip patlamamali.
 const sent=[];assert.equal((await portalOperations(store).deliver(async p=>{sent.push(p);})).sent,1);assert.equal(sent[0].attachment,undefined);assert.deepEqual(sent[0].to,['musteri@example.com']);}finally{store.close();}});

// Panelden acilan talep otomatik onay uretmez: operator kendisi yazisir.
test('staff-created quotes do not mail the customer',async()=>{const store=await createTenantStore();try{const token=store.login('yonetici.demo','AscendDemo!2026').token,admin=store.principal({headers:{cookie:'ascend_sid='+token}});await store.sync(admin,{companies:[carrier('a','Kara','a@example.com')]});quoteService(store).create(admin,request);assert.equal(portalOperations(store).outbox(admin).length,0);}finally{store.close();}});

// Ulke adlari elle yazilir ve veri cogunlukla buyuk harftir. Turkce kucultme
// 'I' harfini noktasiz 'ı' yaptigi icin 'ITALYA' ile 'İtalya' eslesmezdi ve
// talep sebebi gorunmeden taşıyıcı bekler durumda kalirdi.
test('carrier matching survives the dotted and dotless Turkish i',()=>{
 const italya=id=>({id,name:id,isCarrier:true,serviceCountries:['İtalya'],contacts:[{first:'T',transportMode:'Kara',email:'a@example.com'}]});
 for(const yazim of ['İtalya','ITALYA','italya','ıtalya','İTALYA'])
  assert.equal(matchCarriers([italya('a')],{...request,originCountry:yazim}).length,1,'eslesmeli: '+yazim);
 // Farkli ulkeler hala ayrilir; katlama her seyi birbirine karistirmamali.
 assert.equal(matchCarriers([italya('a')],{...request,originCountry:'İspanya'}).length,0);
 assert.equal(matchCarriers([italya('a')],{...request,originCountry:'Almanya'}).length,0);
});
