import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {portalOperations} from '../operations.mjs';
import {createTenantStore} from '../tenant-store.mjs';import {quoteService} from '../quotes.mjs';import {offerService} from '../offers.mjs';import {monitoring} from '../monitoring.mjs';
const restoreScript=join(import.meta.dirname,'..','restore-backup.mjs');
function admin(store){const x=store.login('yonetici.demo','AscendDemo!2026');return store.principal({headers:{cookie:'ascend_sid='+x.token}});}
const request={company:'Customer',person:'Person',email:'customer@example.com',phone:'555',direction:'İthalat',mode:'Kara',originCountry:'Almanya',originCity:'Berlin',originAddress:'Street 1',destinationCountry:'Türkiye',destinationCity:'İstanbul',destinationAddress:'Street 2',goods:'Parts',packages:'2',gross:'200',net:'180',dimensions:'100 x 100 x 100',readyDate:'2026-10-01',incoterm:'FCA'};
const company=(id)=>({id,name:id,address:'Street 1',country:'Türkiye',taxOffice:'Test',taxNo:'1234567890',contacts:[{email:id+'@example.com'}]});
test('accepted offer converts once per request under parallel requests and shares numbering with NCTS',async()=>{const store=await createTenantStore();try{const u=admin(store),year=new Date().getFullYear();await store.sync(u,{companies:[company('sender'),company('receiver'),{...company('carrier'),isCarrier:true,serviceCountries:['Almanya'],contacts:[{email:'carrier@example.com',transportModes:['Kara']}]}],ncts:[{no:'ASC-'+year+'-0008'}]});const q=quoteService(store).create(u,request),service=offerService(store);const o=service.save(u,{quoteId:q.id,carrierId:'carrier',purchase:'100',sale:'150',currency:'EUR',validUntil:'2026-10-01',status:'Kabul edildi'});const body={...o,shipperId:'sender',consigneeId:'receiver'};await assert.rejects(service.convert({...u,role:'Operasyon'},body),e=>e.status===403);const [a,b]=await Promise.all([service.convert(u,body),service.convert(u,body)]);assert.equal(a.fileNo,'ASC-'+year+'-0009');assert.equal(b.fileNo,a.fileNo);assert.equal(store.data(u).shipments.length,1);const saved=store.data(u).shipments[0];assert.equal(saved.salePrice,150);assert.equal(saved.originCity,'Berlin');assert.deepEqual(saved.customerCompanyIds,['sender','receiver']);const other=service.save(u,{quoteId:q.id,carrierId:'carrier',purchase:'90',sale:'140',currency:'EUR',validUntil:'2026-10-01',status:'Kabul edildi'});assert.equal((await service.convert(u,{...other,shipperId:'sender',consigneeId:'receiver'})).fileNo,a.fileNo);}finally{store.close();}});
test('monitoring is admin-only and paid records stop showing overdue reminders',async()=>{const store=await createTenantStore();try{const u=admin(store),m=monitoring(store);quoteService(store);offerService(store);await store.sync(u,{shipments:[{fileNo:'D1',consignee:'Customer',paymentDueDate:'2020-01-01'},{fileNo:'D2',paymentDueDate:'2020-01-01',paymentDate:'2020-01-02'}]});assert.equal(m.list(u).payments.length,1);assert.throws(()=>m.list({...u,role:'Görüntüleme'}),e=>e.status===403);await assert.rejects(m.due(u,{fileNo:'D1',date:'2026-02-31',revision:store.revision()}));await m.due(u,{fileNo:'D1',date:'',revision:store.revision()});assert.equal(m.list(u).payments.length,0);}finally{store.close();}});
test('separate backup copy restores records and PDF bytes to a new database',async()=>{const folder=await mkdtemp(join(tmpdir(),'ascend-restore-'));let store;try{store=await createTenantStore(join(folder,'data','state.json'),{backupDirectory:join(folder,'independent-test-target')});const u=admin(store);await store.sync(u,{shipments:[{fileNo:'RESTORE-1'}]});const pdf=Buffer.from('%PDF-1.7\nRESTORE-TEST');portalOperations(store).upload(u,{module:'shipments',recordId:'RESTORE-1',name:'test.pdf',base64:pdf.toString('base64')});const result=await store.database.makeBackup();assert.equal(result.offsite.status,'verified');const source=join(folder,'independent-test-target',result.file),target=join(folder,'restored','state.json');execFileSync(process.execPath,[restoreScript,source,target]);const restored=new DatabaseSync(target.replace('.json','.sqlite'),{readOnly:true});try{assert.equal(JSON.parse(restored.prepare('SELECT body FROM state').get().body).shipments[0].fileNo,'RESTORE-1');assert.deepEqual(Buffer.from(restored.prepare('SELECT body FROM documents').get().body),pdf);}finally{restored.close();}assert.ok((await readFile(source)).length);assert.throws(()=>execFileSync(process.execPath,[restoreScript,source,target],{stdio:'pipe'}));}finally{store?.close();await rm(folder,{recursive:true,force:true});}});
