import {calculateVolume} from './prototype/quote-volume.mjs';
import {randomUUID} from 'node:crypto';
const required=['company','person','email','phone','direction','mode','originCountry','originCity','originAddress','destinationCountry','destinationCity','destinationAddress','goods','packages','gross','net','dimensions','readyDate','incoterm'];
const normalize=s=>String(s||'').trim().toLocaleLowerCase('tr-TR');
export function validateQuote(input){const data={};for(const key of required){data[key]=String(input[key]??'').trim();if(!data[key])throw Error('Zorunlu teklif alanı eksik: '+key);if(data[key].length>2000)throw Error('Alan çok uzun');}if(!/^\S+@\S+\.\S+$/.test(data.email))throw Error('E-posta adresi geçersiz');if(!['İthalat','İhracat'].includes(data.direction)||!['Hava','Kara','Deniz','Demiryolu'].includes(data.mode))throw Error('Yön ve taşıma türü seçin');for(const k of ['packages','gross','net'])if(!Number.isFinite(Number(data[k]))||Number(data[k])<=0)throw Error('Kap, kilo ve hacim sıfırdan büyük olmalı');if(!Number.isInteger(Number(data.packages))||Number(data.net)>Number(data.gross))throw Error('Kap tam sayı olmalı; net kilo brüt kiloyu aşamaz');if(!/^\d{4}-\d{2}-\d{2}$/.test(data.readyDate)||!Number.isFinite(Date.parse(data.readyDate)))throw Error('Yükün hazır olacağı tarih gerekli');data.volume=String(calculateVolume(data.dimensions,data.packages));return data;}
export function matchCarriers(companies,data){const country=data.direction==='İthalat'?data.originCountry:data.destinationCountry;return companies.filter(c=>c.isCarrier===true&&(c.serviceCountries||[]).some(x=>normalize(x)===normalize(country))).map(c=>({company:c,contacts:(c.contacts||[]).filter(p=>(p.transportModes||[p.transportMode]).includes(data.mode)&&/^\S+@\S+\.\S+$/.test(p.email||''))})).filter(c=>c.contacts.length);}
export function quoteService(store){const db=store.database.db;db.exec('CREATE TABLE IF NOT EXISTS quote_requests(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,created_by TEXT NOT NULL,status TEXT NOT NULL,body TEXT NOT NULL);CREATE TABLE IF NOT EXISTS quote_drafts(id TEXT PRIMARY KEY,quote_id TEXT NOT NULL,carrier_id TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL,UNIQUE(quote_id,carrier_id));');const admin=u=>{if(u?.role!=='Yönetici')throw Object.assign(Error('Yetkisiz'),{status:403});};const staff=u=>{if(!u||['Müşteri','Görüntüleme'].includes(u.role))throw Object.assign(Error('Yetkisiz'),{status:403});};
 function prepare(id,u){staff(u);const row=db.prepare('SELECT * FROM quote_requests WHERE id=?').get(id);if(!row)throw Error('Talep bulunamadı');const data=JSON.parse(row.body),matches=matchCarriers(store.data(u).companies,data);for(const {company,contacts} of matches){const addresses=[...new Set(contacts.map(c=>c.email.trim().toLowerCase()))];const payload={to:addresses.slice(0,1),cc:addresses.slice(1),subject:'Navlun fiyat talebi — '+id, text:['Sayın Yetkili,','Aşağıdaki taşıma için navlun, yerel masraflar, transit süre ve teklif geçerliliğini iletmenizi rica ederiz. ETA (tahmini varış tarihi) bilgisini gün/ay/yıl olarak özellikle belirtmenizi önemle rica ederiz.',...['mode','originCountry','originCity','originAddress','destinationCountry','destinationCity','destinationAddress','goods','packages','gross','net','volume','dimensions','readyDate','incoterm'].map(k=>({mode:'Taşıma türü',originCountry:'Çıkış ülkesi',originCity:'Çıkış şehri',originAddress:'Yükleme adresi',destinationCountry:'Varış ülkesi',destinationCity:'Varış şehri',destinationAddress:'Teslim adresi',goods:'Eşya',packages:'Kap',gross:'Brüt kg',net:'Net kg',volume:'Hacim m³',dimensions:'Ölçüler',readyDate:'Eşyanın Hazır Olma Tarihi',incoterm:'Teslim şekli'})[k]+': '+data[k]),'ASCEND Lojistik','info@ascendlojistik.com'].join('\n')};db.prepare("INSERT OR IGNORE INTO quote_drafts VALUES(?,?,?,?,'draft')").run(randomUUID(),id,String(company.id||company.name),JSON.stringify(payload));}const status=matches.length?'drafts-ready':'needs-carrier';db.prepare('UPDATE quote_requests SET status=? WHERE id=?').run(status,id);store.database.audit(u.username,'quote.drafted',{id,carrierCount:matches.length});return {id,status,carrierCount:matches.length,missingCountry:matches.length?null:(data.direction==='İthalat'?data.originCountry:data.destinationCountry),mode:data.mode};}
 // Siteden gelen talebi gonderen kisiye ozetini geri yollar. Yalniz musterinin
 // kendi girdigi alanlar yazilir; hangi acenteye sorulacagi musteriye acilmaz.
 function acknowledge(id,data){const payload={kind:'quote-ack',to:[data.email.trim().toLowerCase()],cc:[],subject:'Talebiniz alındı — '+id,
  text:['Sayın '+data.person+',','','Fiyat talebiniz ekibimize ulaştı. Referans numaranız: '+id,'En kısa sürede size dönüş yapacağız.','','Girdiğiniz bilgiler:',
   ...[['direction','İşlem yönü'],['mode','Taşıma türü'],['originCountry','Çıkış ülkesi'],['originCity','Çıkış şehri'],['destinationCountry','Varış ülkesi'],['destinationCity','Varış şehri'],['goods','Eşya'],['packages','Kap'],['gross','Brüt kg'],['net','Net kg'],['volume','Hacim m³'],['readyDate','Eşyanın hazır olma tarihi'],['incoterm','Teslim şekli']].map(([k,label])=>label+': '+data[k]),
   '','Bir yanlışlık varsa bu e-postayı yanıtlayabilirsiniz.','','ASCEND Lojistik','info@ascendlojistik.com'].join('\n')};
  db.prepare("INSERT OR IGNORE INTO outbox VALUES(?,?,?,0,?,?,NULL)").run(randomUUID(),'quote-ack:'+id,'waiting-provider',new Date().toISOString(),JSON.stringify(payload));}
 return {prepare,create(u,input){staff(u);const data=validateQuote(input),id='TEK-'+randomUUID().slice(0,8).toUpperCase();db.prepare("INSERT INTO quote_requests VALUES(?,?,?,'new',?)").run(id,new Date().toISOString(),u.username,JSON.stringify(data));return prepare(id,u);},intake(input){const data=validateQuote(input),id='TEK-'+randomUUID().slice(0,8).toUpperCase();db.prepare("INSERT INTO quote_requests VALUES(?,?,?,'new',?)").run(id,new Date().toISOString(),'website',JSON.stringify(data));prepare(id,{username:'website',role:'system'});acknowledge(id,data);return {id,status:'received'};}, // Form herkese aciktir; yanlis doldurulmus, tekrarlanmis veya istenmeyen
 // talepler gelir ve listede birikir. Yonetici bunlari kaldirabilmelidir.
 // Kayit silinir ama denetim gunlugune kim neyi kaldirdi yazilir; teklife
 // donusmus bir talep korunur, cunku teklif ona baglidir.
 dismiss(u,b){admin(u);const id=String(b?.id||'').trim();if(!id)throw Error('Talep kimliği gerekli');const row=db.prepare('SELECT * FROM quote_requests WHERE id=?').get(id);if(!row)throw Error('Talep bulunamadı');let linked=0;try{linked=db.prepare('SELECT COUNT(*) c FROM offers WHERE quote_id=?').get(id).c;}catch{linked=0;}if(linked)throw Error('Bu talepten teklif oluşturulmuş; kaldırılamaz.');db.prepare('DELETE FROM quote_drafts WHERE quote_id=?').run(id);db.prepare('DELETE FROM quote_requests WHERE id=?').run(id);store.database.audit(u.username,'quote.dismissed',{id,company:JSON.parse(row.body).company??''});return {ok:true};},
 list(u){staff(u);return db.prepare('SELECT * FROM quote_requests ORDER BY created_at DESC LIMIT 100').all().map(r=>({...r,body:JSON.parse(r.body),drafts:db.prepare('SELECT * FROM quote_drafts WHERE quote_id=?').all(r.id).map(d=>({...d,body:{...JSON.parse(d.body),text:JSON.parse(d.body).text.replace(/Hazır tarihi/g,'Eşyanın Hazır Olma Tarihi')+(JSON.parse(d.body).text.includes('ETA')?'':'\nETA (tahmini varış tarihi) bilgisini gün/ay/yıl olarak özellikle belirtmenizi önemle rica ederiz.')}}))}));},approve(u,b){admin(u);if(b.reviewed!==true)throw Error('Önce taslağı kontrol edin');const row=db.prepare('SELECT * FROM quote_drafts WHERE id=?').get(b.id);if(!row)throw Error('Taslak bulunamadı');const payload=JSON.parse(row.body);if(!String(b.subject||'').trim()||!String(b.text||'').trim())throw Error('Konu ve metin gerekli');payload.subject=String(b.subject).slice(0,200);payload.text=String(b.text).slice(0,15000);db.prepare("INSERT OR IGNORE INTO outbox VALUES(?,?,?,0,?,?,NULL)").run(randomUUID(),'quote:'+row.id,'waiting-provider',new Date().toISOString(),JSON.stringify({...payload,kind:'quote'}));db.prepare("UPDATE quote_drafts SET status='approved' WHERE id=?").run(row.id);store.database.audit(u.username,'quote.approved',{id:row.id,carrier:row.carrier_id});return {status:'waiting-provider'};}};
}
