/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenizyoluTasimaciligiRouteImport } from './routes/denizyolu-tasimaciligi'
import { Route as DijitalCozumlerRouteImport } from './routes/dijital-cozumler'
import { Route as GemiAcenteligiRouteImport } from './routes/gemi-acenteligi'
import { Route as GlobalAgRouteImport } from './routes/global-ag'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HavayoluTasimaciligiRouteImport } from './routes/havayolu-tasimaciligi'
import { Route as HizmetlerimizRouteImport } from './routes/hizmetlerimiz'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KarayoluTasimaciligiRouteImport } from './routes/karayolu-tasimaciligi'
import { Route as MultimodalTasimacilikRouteImport } from './routes/multimodal-tasimacilik'
import { Route as ParsiyelTasimacilikRouteImport } from './routes/parsiyel-tasimacilik'
import { Route as ProjeTasimaciligiRouteImport } from './routes/proje-tasimaciligi'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnDigitalSolutionsRouteImport } from './routes/en/digital-solutions'
import { Route as EnGlobalNetworkRouteImport } from './routes/en/global-network'
import { Route as EnServicesRouteImport } from './routes/en/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenizyoluTasimaciligiRoute = DenizyoluTasimaciligiRouteImport.update({
  id: '/denizyolu-tasimaciligi',
  path: '/denizyolu-tasimaciligi',
  getParentRoute: () => rootRouteImport,
} as any)
const DijitalCozumlerRoute = DijitalCozumlerRouteImport.update({
  id: '/dijital-cozumler',
  path: '/dijital-cozumler',
  getParentRoute: () => rootRouteImport,
} as any)
const GemiAcenteligiRoute = GemiAcenteligiRouteImport.update({
  id: '/gemi-acenteligi',
  path: '/gemi-acenteligi',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalAgRoute = GlobalAgRouteImport.update({
  id: '/global-ag',
  path: '/global-ag',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HavayoluTasimaciligiRoute = HavayoluTasimaciligiRouteImport.update({
  id: '/havayolu-tasimaciligi',
  path: '/havayolu-tasimaciligi',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizRoute = HizmetlerimizRouteImport.update({
  id: '/hizmetlerimiz',
  path: '/hizmetlerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KarayoluTasimaciligiRoute = KarayoluTasimaciligiRouteImport.update({
  id: '/karayolu-tasimaciligi',
  path: '/karayolu-tasimaciligi',
  getParentRoute: () => rootRouteImport,
} as any)
const MultimodalTasimacilikRoute = MultimodalTasimacilikRouteImport.update({
  id: '/multimodal-tasimacilik',
  path: '/multimodal-tasimacilik',
  getParentRoute: () => rootRouteImport,
} as any)
const ParsiyelTasimacilikRoute = ParsiyelTasimacilikRouteImport.update({
  id: '/parsiyel-tasimacilik',
  path: '/parsiyel-tasimacilik',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjeTasimaciligiRoute = ProjeTasimaciligiRouteImport.update({
  id: '/proje-tasimaciligi',
  path: '/proje-tasimaciligi',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnDigitalSolutionsRoute = EnDigitalSolutionsRouteImport.update({
  id: '/en/digital-solutions',
  path: '/en/digital-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGlobalNetworkRoute = EnGlobalNetworkRouteImport.update({
  id: '/en/global-network',
  path: '/en/global-network',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denizyolu-tasimaciligi': typeof DenizyoluTasimaciligiRoute
  '/dijital-cozumler': typeof DijitalCozumlerRoute
  '/gemi-acenteligi': typeof GemiAcenteligiRoute
  '/global-ag': typeof GlobalAgRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/havayolu-tasimaciligi': typeof HavayoluTasimaciligiRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
  '/karayolu-tasimaciligi': typeof KarayoluTasimaciligiRoute
  '/multimodal-tasimacilik': typeof MultimodalTasimacilikRoute
  '/parsiyel-tasimacilik': typeof ParsiyelTasimacilikRoute
  '/proje-tasimaciligi': typeof ProjeTasimaciligiRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/digital-solutions': typeof EnDigitalSolutionsRoute
  '/en/global-network': typeof EnGlobalNetworkRoute
  '/en/services': typeof EnServicesRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denizyolu-tasimaciligi': typeof DenizyoluTasimaciligiRoute
  '/dijital-cozumler': typeof DijitalCozumlerRoute
  '/gemi-acenteligi': typeof GemiAcenteligiRoute
  '/global-ag': typeof GlobalAgRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/havayolu-tasimaciligi': typeof HavayoluTasimaciligiRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
  '/karayolu-tasimaciligi': typeof KarayoluTasimaciligiRoute
  '/multimodal-tasimacilik': typeof MultimodalTasimacilikRoute
  '/parsiyel-tasimacilik': typeof ParsiyelTasimacilikRoute
  '/proje-tasimaciligi': typeof ProjeTasimaciligiRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/digital-solutions': typeof EnDigitalSolutionsRoute
  '/en/global-network': typeof EnGlobalNetworkRoute
  '/en/services': typeof EnServicesRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/denizyolu-tasimaciligi': typeof DenizyoluTasimaciligiRoute
  '/dijital-cozumler': typeof DijitalCozumlerRoute
  '/gemi-acenteligi': typeof GemiAcenteligiRoute
  '/global-ag': typeof GlobalAgRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/havayolu-tasimaciligi': typeof HavayoluTasimaciligiRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
  '/karayolu-tasimaciligi': typeof KarayoluTasimaciligiRoute
  '/multimodal-tasimacilik': typeof MultimodalTasimacilikRoute
  '/parsiyel-tasimacilik': typeof ParsiyelTasimacilikRoute
  '/proje-tasimaciligi': typeof ProjeTasimaciligiRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/digital-solutions': typeof EnDigitalSolutionsRoute
  '/en/global-network': typeof EnGlobalNetworkRoute
  '/en/services': typeof EnServicesRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denizyolu-tasimaciligi'
    | '/dijital-cozumler'
    | '/gemi-acenteligi'
    | '/global-ag'
    | '/hakkimizda'
    | '/havayolu-tasimaciligi'
    | '/hizmetlerimiz'
    | '/iletisim'
    | '/karayolu-tasimaciligi'
    | '/multimodal-tasimacilik'
    | '/parsiyel-tasimacilik'
    | '/proje-tasimaciligi'
    | '/en/about'
    | '/en/contact'
    | '/en/digital-solutions'
    | '/en/global-network'
    | '/en/services'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denizyolu-tasimaciligi'
    | '/dijital-cozumler'
    | '/gemi-acenteligi'
    | '/global-ag'
    | '/hakkimizda'
    | '/havayolu-tasimaciligi'
    | '/hizmetlerimiz'
    | '/iletisim'
    | '/karayolu-tasimaciligi'
    | '/multimodal-tasimacilik'
    | '/parsiyel-tasimacilik'
    | '/proje-tasimaciligi'
    | '/en/about'
    | '/en/contact'
    | '/en/digital-solutions'
    | '/en/global-network'
    | '/en/services'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/denizyolu-tasimaciligi'
    | '/dijital-cozumler'
    | '/gemi-acenteligi'
    | '/global-ag'
    | '/hakkimizda'
    | '/havayolu-tasimaciligi'
    | '/hizmetlerimiz'
    | '/iletisim'
    | '/karayolu-tasimaciligi'
    | '/multimodal-tasimacilik'
    | '/parsiyel-tasimacilik'
    | '/proje-tasimaciligi'
    | '/en/about'
    | '/en/contact'
    | '/en/digital-solutions'
    | '/en/global-network'
    | '/en/services'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenizyoluTasimaciligiRoute: typeof DenizyoluTasimaciligiRoute
  DijitalCozumlerRoute: typeof DijitalCozumlerRoute
  GemiAcenteligiRoute: typeof GemiAcenteligiRoute
  GlobalAgRoute: typeof GlobalAgRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HavayoluTasimaciligiRoute: typeof HavayoluTasimaciligiRoute
  HizmetlerimizRoute: typeof HizmetlerimizRoute
  IletisimRoute: typeof IletisimRoute
  KarayoluTasimaciligiRoute: typeof KarayoluTasimaciligiRoute
  MultimodalTasimacilikRoute: typeof MultimodalTasimacilikRoute
  ParsiyelTasimacilikRoute: typeof ParsiyelTasimacilikRoute
  ProjeTasimaciligiRoute: typeof ProjeTasimaciligiRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnDigitalSolutionsRoute: typeof EnDigitalSolutionsRoute
  EnGlobalNetworkRoute: typeof EnGlobalNetworkRoute
  EnServicesRoute: typeof EnServicesRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denizyolu-tasimaciligi': {
      id: '/denizyolu-tasimaciligi'
      path: '/denizyolu-tasimaciligi'
      fullPath: '/denizyolu-tasimaciligi'
      preLoaderRoute: typeof DenizyoluTasimaciligiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dijital-cozumler': {
      id: '/dijital-cozumler'
      path: '/dijital-cozumler'
      fullPath: '/dijital-cozumler'
      preLoaderRoute: typeof DijitalCozumlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemi-acenteligi': {
      id: '/gemi-acenteligi'
      path: '/gemi-acenteligi'
      fullPath: '/gemi-acenteligi'
      preLoaderRoute: typeof GemiAcenteligiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-ag': {
      id: '/global-ag'
      path: '/global-ag'
      fullPath: '/global-ag'
      preLoaderRoute: typeof GlobalAgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/havayolu-tasimaciligi': {
      id: '/havayolu-tasimaciligi'
      path: '/havayolu-tasimaciligi'
      fullPath: '/havayolu-tasimaciligi'
      preLoaderRoute: typeof HavayoluTasimaciligiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz': {
      id: '/hizmetlerimiz'
      path: '/hizmetlerimiz'
      fullPath: '/hizmetlerimiz'
      preLoaderRoute: typeof HizmetlerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karayolu-tasimaciligi': {
      id: '/karayolu-tasimaciligi'
      path: '/karayolu-tasimaciligi'
      fullPath: '/karayolu-tasimaciligi'
      preLoaderRoute: typeof KarayoluTasimaciligiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multimodal-tasimacilik': {
      id: '/multimodal-tasimacilik'
      path: '/multimodal-tasimacilik'
      fullPath: '/multimodal-tasimacilik'
      preLoaderRoute: typeof MultimodalTasimacilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsiyel-tasimacilik': {
      id: '/parsiyel-tasimacilik'
      path: '/parsiyel-tasimacilik'
      fullPath: '/parsiyel-tasimacilik'
      preLoaderRoute: typeof ParsiyelTasimacilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proje-tasimaciligi': {
      id: '/proje-tasimaciligi'
      path: '/proje-tasimaciligi'
      fullPath: '/proje-tasimaciligi'
      preLoaderRoute: typeof ProjeTasimaciligiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/digital-solutions': {
      id: '/en/digital-solutions'
      path: '/en/digital-solutions'
      fullPath: '/en/digital-solutions'
      preLoaderRoute: typeof EnDigitalSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/global-network': {
      id: '/en/global-network'
      path: '/en/global-network'
      fullPath: '/en/global-network'
      preLoaderRoute: typeof EnGlobalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services': {
      id: '/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenizyoluTasimaciligiRoute: DenizyoluTasimaciligiRoute,
  DijitalCozumlerRoute: DijitalCozumlerRoute,
  GemiAcenteligiRoute: GemiAcenteligiRoute,
  GlobalAgRoute: GlobalAgRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HavayoluTasimaciligiRoute: HavayoluTasimaciligiRoute,
  HizmetlerimizRoute: HizmetlerimizRoute,
  IletisimRoute: IletisimRoute,
  KarayoluTasimaciligiRoute: KarayoluTasimaciligiRoute,
  MultimodalTasimacilikRoute: MultimodalTasimacilikRoute,
  ParsiyelTasimacilikRoute: ParsiyelTasimacilikRoute,
  ProjeTasimaciligiRoute: ProjeTasimaciligiRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnDigitalSolutionsRoute: EnDigitalSolutionsRoute,
  EnGlobalNetworkRoute: EnGlobalNetworkRoute,
  EnServicesRoute: EnServicesRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
